### ISSUE TITLE
Terminformular: Key?

### ISSUE THREAD

**Issue by astro** [offenesdresden/offenesdresden.de#3]
Ich wusste mit Key nicht viel anzufangen, habe einen Pre-Shared Key erwartet und begonnen den Code nochmal zu lesen. Erst dann habe ich meine Mails gecheckt. Man könnte das auch "Bestätigungscode" oder so nennen.

**Comment by jklmnn** [comment]
Das muss ich mir evtl. noch mal anschauen. Ich bin leider kein Experte für Usability. ;)

**Comment by jklmnn** [comment]
Ich hab noch mal den Umlaut rausgemacht.
Die neue Datei ist jetzt auf dem Server.
Und ich hab bei der Gelegenheit gleich mal die Emailaddresse berichtigt.

**Comment by astro** [comment]
Man kann in HTML ein Encoding angeben.

**Comment by jklmnn** [comment]
Hab ich gemacht, gleich bei allen von mir, bei denen es gefehlt hat.
21d61774df0d6c179d3ff86e301e6b66935515ab
